/*
 * Revenium Metering API
 *
 * Revenium Metering API
 *
 * API version: 1.14.0-SNAPSHOT
 * Contact: info@revenium.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package metering

type ApiEventDto struct {
	RequestId string `json:"requestId,omitempty"`
	EventType string `json:"eventType,omitempty"`
	AssetId string `json:"assetId,omitempty"`
	ProductKey string `json:"productKey,omitempty"`
	Application string `json:"application,omitempty"`
	Method string `json:"method,omitempty"`
	CurrentMillis int64 `json:"currentMillis,omitempty"`
	Uri string `json:"uri,omitempty"`
	ElapsedTime int64 `json:"elapsedTime,omitempty"`
	Metadata string `json:"metadata,omitempty"`
	ResponseCode int32 `json:"responseCode"`
	RequestMessageSize int64 `json:"requestMessageSize,omitempty"`
	ResponseMessageSize int64 `json:"responseMessageSize,omitempty"`
	ContentType string `json:"contentType,omitempty"`
	RemoteHost string `json:"remoteHost,omitempty"`
	UserAgent string `json:"userAgent,omitempty"`
	CorrelationId string `json:"correlationId,omitempty"`
	BackendLatency float64 `json:"backendLatency,omitempty"`
	ClientId string `json:"clientId,omitempty"`
	Source string `json:"source,omitempty"`
}
