/*
 * Revenium Metering API
 *
 * Revenium Metering API
 *
 * API version: 1.14.0-SNAPSHOT
 * Contact: info@revenium.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package metering

// Dynamic metering elements
type ElementDto struct {
	Name string `json:"name"`
	Value string `json:"value"`
}
